/* ═══════════════════════════════════════════════════
   MOONLIGHT ACCESSORIES — SHOP CONFIG
   Shared by index.html and the policy pages.
   ═══════════════════════════════════════════════════ */

/* The shop's WhatsApp number in international form, digits only, no + or
   spaces. Example: 0300 1234567 becomes '923001234567'.

   While this is empty, every WhatsApp button and link on the site stays
   hidden, so customers are never shown a number that does not answer.
   Set it here once and it applies everywhere.                            */
const WHATSAPP = '923104463808';

/* Delivery. These are what the customer is shown; the server recalculates
   the real figures on every order, so change them in both places.        */
const SHIP_FEE  = 200;
const FREE_SHIP = 5000;

function waLink(text) {
  return 'https://wa.me/' + WHATSAPP + (text ? '?text=' + encodeURIComponent(text) : '');
}

/* Points every [data-wa] link at WhatsApp and reveals every .wa-only
   element — or leaves them all hidden when no number is configured. */
function applyWhatsAppLinks() {
  if (!WHATSAPP) return;
  document.querySelectorAll('[data-wa]').forEach(function (a) {
    a.href = waLink(a.dataset.wa || 'Assalam o Alaikum! I would like to ask about your hair extensions.');
  });
  document.querySelectorAll('.wa-only').forEach(function (el) {
    el.style.display = el.classList.contains('wa-float') ? 'flex' : '';
  });
}

document.addEventListener('DOMContentLoaded', applyWhatsAppLinks);

/* ── VISITOR HEARTBEAT ───────────────────────────────────────────────
   Tells the admin dashboard how many people are on the site right now.

   The id below is random, generated by the browser, and lives only until
   the tab is closed. No name, no IP, nothing that identifies anybody —
   it exists purely so two tabs are not counted as two people.          */
(function () {
  var API = (location.hostname.endsWith('moonlightaccessories.pk') ? '' :
             (location.hostname === 'localhost' || location.hostname === '127.0.0.1')
               ? 'http://localhost:5000' : 'https://moonlightaccessories.pk') + '/api/v1/track';

  var sid;
  try {
    sid = sessionStorage.getItem('ml_sid');
    if (!sid) {
      sid = Math.random().toString(36).slice(2) + Date.now().toString(36);
      sessionStorage.setItem('ml_sid', sid);
    }
  } catch (e) { return; }          // private mode with storage blocked: skip

  function ping() {
    if (document.visibilityState !== 'visible') return;   // no pings from background tabs
    try {
      fetch(API, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sid: sid,
          path: location.pathname + location.hash,
          title: document.title,
          referrer: document.referrer || '',
        }),
        keepalive: true,
      }).catch(function () {});
    } catch (e) {}
  }

  document.addEventListener('DOMContentLoaded', ping);
  document.addEventListener('visibilitychange', ping);
  setInterval(ping, 60000);        // once a minute keeps "active now" accurate
})();
